name: pikafish_engine
description: The Flutter plugin for PIKAFISH (base on Stockfish), A well-known Chinese chess open source engine.
version: 1.0.4
repository: https://github.com/hezhaoyun/flutter_pikafish
homepage: https://mdevs.cn

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  ffi: ^2.0.0
  flutter:
    sdk: flutter
  logging: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: cn.mdevs.cchess.engine.pikafish
        pluginClass: PikafishPlugin
      ios:
        pluginClass: PikafishPlugin
